### ISSUE TITLE
@nestjs/swagger not working

### ISSUE THREAD

**Issue by hoangnq3004** [Skn0tt/nextjs-nestjs-integration-example#1]
Hi @Skn0tt !

Thanks for [your tutorial](https://simonknott.de/articles/Integrating-NextJS-with-NestJS.html)!

I want to integrate @nestjs/swagger for auto documentation in my project but it not run

Here is my code

```
const options = new DocumentBuilder()
    .setTitle('API')
    .setDescription('API')
    .setVersion('1.0') 
    .addTag('api')
    .build();
const document = SwaggerModule.createDocument(app, options);
SwaggerModule.setup('docs', app, document);
```

When I navigate to http://localhost:3000/api/docs/static/index.html, it's return 404 page.

How I can fix it? Please help!

**Comment by Skn0tt** [comment]
Hi @hoangnq3004,  I'm happy you liked the tutorial.

Some guesses: Did you properly set up Decorators (e.g. using [WarnerHooh/babel-plugin-parameter-decorator](https://github.com/WarnerHooh/babel-plugin-parameter-decorator)) ? I had some problems with that myself. Maybe there's something in your logs about that.

Could you provide a minimal reproduction repository? That'd make it a lot easier for me to help you.

**Comment by hoangnq3004** [comment]
Thanks for your reply!

Here is my repository https://github.com/hoangnq3004/tima

**Comment by Skn0tt** [comment]
In case anybody finds this issue and wonders about the error:

The base route you pass to `SwaggerModule.setup` (in the code above, that's `docs`) doesn't take the global prefix into account that's set  [here](https://github.com/Skn0tt/nextjs-nestjs-integration-example/blob/5baf0f2f119189edf02d73212e9003a94ce37098/src/backend/main.ts#L16) (see below).
So you'll need to set it to `api/docs` to make it work.

---

(I guess it's because the SwaggerModule  hooks up to straight to express, without going through NestJS' routing mechanism first. That could be the reason why Swaggers routes don't show up in NestJS' route map, at least.)

**Comment by hoangnq3004** [comment]
Thank you very much!

**Comment by Skn0tt** [comment]
I've placed a link to this issue at the bottom of the blog post for future reference :)
